export const movies = [
	{
		id: 1,
		title: '12 Angry Men',
		genre: 'Drama',
		director: 'Sidney Lumet',
		yearReleased: '1957',
	},
	{
		id: 2,
		title: '2001: A Space Odyssey',
		genre: 'Science Fiction',
		director: 'Stanley Kubrick',
		yearReleased: '1968',
	},
	{
		id: 3,
		title: 'Airplane!',
		genre: 'Comedy',
		director: 'Jim Abrahams, David Zucker, Jerry Zucker',
		yearReleased: '1980',
	},
	{
		id: 4,
		title: 'Alien',
		genre: 'Horror',
		director: 'Ridley Scott',
		yearReleased: '1979',
	},
	{
		id: 5,
		title: 'Aliens',
		genre: 'Action',
		director: 'James Cameron',
		yearReleased: '1986',
	},
	{
		id: 6,
		title: 'Arrival',
		genre: 'Science Fiction',
		director: 'Denis Villeneuve',
		yearReleased: '2016',
	},
	{
		id: 7,
		title: 'Blade Runner',
		genre: 'Science Fiction',
		director: 'Ridley Scott',
		yearReleased: '1982',
	},
	{
		id: 8,
		title: 'Die Hard',
		genre: 'Action',
		director: 'John McTiernan',
		yearReleased: '1988',
	},
	{
		id: 9,
		title: 'Donnie Darko',
		genre: 'Science Fiction',
		director: 'Richard Kelly',
		yearReleased: '2001',
	},
	{
		id: 10,
		title: 'Eternal Sunshine of the Spotless Mind',
		genre: 'Science Fiction',
		director: 'Michel Gondry',
		yearReleased: '2004',
	},
	{
		id: 11,
		title: "Ferris Bueller's Day Off",
		genre: 'Comedy',
		director: 'John Hughes',
		yearReleased: '1986',
	},
	{
		id: 12,
		title: 'Forrest Gump',
		genre: 'Drama',
		director: 'Robert Zemeckis',
		yearReleased: '1994',
	},
	{
		id: 13,
		title: 'Get Out',
		genre: 'Horror',
		director: 'Jordan Peele',
		yearReleased: '2017',
	},
	{
		id: 14,
		title: 'Gone Girl',
		genre: 'Mystery',
		director: 'David Fincher',
		yearReleased: '2014',
	},
	{
		id: 15,
		title: 'Good Will Hunting',
		genre: 'Drama',
		director: 'Gus Van Sant',
		yearReleased: '1997',
	},
	{
		id: 16,
		title: 'Groundhog Day',
		genre: 'Comedy',
		director: 'Harold Ramis',
		yearReleased: '1993',
	},
	{
		id: 17,
		title: 'Halloween',
		genre: 'Horror',
		director: 'John Carpenter',
		yearReleased: '1978',
	},
	{
		id: 18,
		title: 'Inception',
		genre: 'Science Fiction',
		director: 'Christopher Nolan',
		yearReleased: '2010',
	},
	{
		id: 19,
		title: 'Jaws',
		genre: 'Thriller',
		director: 'Steven Spielberg',
		yearReleased: '1975',
	},
	{
		id: 20,
		title: 'Jurassic Park',
		genre: 'Adventure',
		director: 'Steven Spielberg',
		yearReleased: '1993',
	},
	{
		id: 21,
		title: 'Knives Out',
		genre: 'Mystery',
		director: 'Rian Johnson',
		yearReleased: '2019',
	},
	{
		id: 22,
		title: 'Labyrinth',
		genre: 'Fantasy',
		director: 'Jim Henson',
		yearReleased: '1986',
	},
	{
		id: 23,
		title: 'Memento',
		genre: 'Thriller',
		director: 'Christopher Nolan',
		yearReleased: '2000',
	},
	{
		id: 24,
		title: 'Monty Python and the Holy Grail',
		genre: 'Comedy',
		director: 'Terry Gilliam, Terry Jones',
		yearReleased: '1975',
	},
	{
		id: 25,
		title: 'North by Northwest',
		genre: 'Thriller',
		director: 'Alfred Hitchcock',
		yearReleased: '1959',
	},
	{
		id: 26,
		title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
		genre: 'Adventure',
		director: 'Gore Verbinski',
		yearReleased: '2003',
	},
	{
		id: 27,
		title: 'Prisoners',
		genre: 'Mystery',
		director: 'Denis Villeneuve',
		yearReleased: '2013',
	},
	{
		id: 28,
		title: 'Psycho',
		genre: 'Horror',
		director: 'Alfred Hitchcock',
		yearReleased: '1960',
	},
	{
		id: 29,
		title: 'Pulp Fiction',
		genre: 'Drama',
		director: 'Quentin Tarantino',
		yearReleased: '1994',
	},
	{
		id: 30,
		title: 'Raiders of the Lost Ark',
		genre: 'Adventure',
		director: 'Steven Spielberg',
		yearReleased: '1981',
	},
	{
		id: 31,
		title: "Schindler's List",
		genre: 'Drama',
		director: 'Steven Spielberg',
		yearReleased: '1993',
	},
	{
		id: 32,
		title: 'Se7en',
		genre: 'Thriller',
		director: 'David Fincher',
		yearReleased: '1995',
	},
	{
		id: 33,
		title: 'Shaun of the Dead',
		genre: 'Comedy',
		director: 'Edgar Wright',
		yearReleased: '2004',
	},
	{
		id: 34,
		title: 'The Big Lebowski',
		genre: 'Comedy',
		director: 'Joel Coen, Ethan Coen',
		yearReleased: '1998',
	},
	{
		id: 35,
		title: 'The Dark Knight',
		genre: 'Action',
		director: 'Christopher Nolan',
		yearReleased: '2008',
	},
	{
		id: 36,
		title: 'The Exorcist',
		genre: 'Horror',
		director: 'William Friedkin',
		yearReleased: '1973',
	},
	{
		id: 37,
		title: 'The Fifth Element',
		genre: 'Science Fiction',
		director: 'Luc Besson',
		yearReleased: '1997',
	},
	{
		id: 38,
		title: 'The Godfather',
		genre: 'Drama',
		director: 'Francis Ford Coppola',
		yearReleased: '1972',
	},
	{
		id: 39,
		title: 'The Lord of the Rings: The Return of the King',
		genre: 'Fantasy',
		director: 'Peter Jackson',
		yearReleased: '2003',
	},
	{
		id: 40,
		title: 'The Matrix',
		genre: 'Action',
		director: 'Lana Wachowski, Lilly Wachowski',
		yearReleased: '1999',
	},
	{
		id: 41,
		title: 'The Shawshank Redemption',
		genre: 'Drama',
		director: 'Frank Darabont',
		yearReleased: '1994',
	},
	{
		id: 42,
		title: 'The Silence of the Lambs',
		genre: 'Thriller',
		director: 'Jonathan Demme',
		yearReleased: '1991',
	},
	{
		id: 43,
		title: 'The Usual Suspects',
		genre: 'Mystery',
		director: 'Bryan Singer',
		yearReleased: '1995',
	},
	{
		id: 44,
		title: 'The Wizard of Oz',
		genre: 'Fantasy',
		director: 'Victor Fleming',
		yearReleased: '1939',
	},
	{
		id: 45,
		title: 'Zodiac',
		genre: 'Mystery',
		director: 'David Fincher',
		yearReleased: '2007',
	},
];
